/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

sourceSets {
    testFixtures {
        java {
            setSrcDirs(listOf("src/fixtures/java"))
        }
        resources {
            setSrcDirs(listOf("src/fixtures/resources"))
        }
    }
}

dependencies {
    api(libs.jaxb.api)
    api(libs.slf4j.api)
    implementation(libs.trove4j)
    implementation("com.vdurmont:emoji-java:5.1.1")
    implementation("com.carrotsearch:hppc:0.8.2")
    implementation(libs.jackson.databind)
    implementation(libs.dumonts.hunspell)
    implementation(libs.guava)
    implementation(libs.hankcs)
    implementation(libs.language.detector)
    implementation(libs.commons.logging)
    implementation(libs.commons.validator)
    implementation("io.github.resilience4j:resilience4j-circuitbreaker:1.7.1")
    implementation("io.github.resilience4j:resilience4j-micrometer:1.7.1")
    implementation(libs.opentelemetry.api)
    implementation(libs.opentelemetry.semconv)
    implementation(libs.grpc.stub)
    implementation(libs.grpc.netty.shaded)
    implementation(libs.grpc.protobuf)
    implementation("io.micrometer:micrometer-registry-prometheus:1.7.1")
    implementation("io.prometheus:simpleclient:0.12.0")
    implementation("io.prometheus:simpleclient_guava:0.12.0")
    implementation(libs.javax.activation.api)
    implementation(libs.javax.annotation.api)
    implementation("javax.measure:unit-api:1.0")
    implementation("net.loomchild:segment:2.0.1")
    implementation(libs.commons.lang)
    implementation(libs.commons.pool)
    implementation(libs.commons.text)
    implementation(libs.lucene.core)
    implementation(libs.lucene.backward.codecs)
    implementation(libs.morfologik.fsa)
    implementation(libs.morfologik.builders)
    implementation(libs.morfologik.speller)
    implementation(libs.morfologik.stemming)
    implementation(libs.jaxb.runtime)
    implementation(libs.jetbrains.annotations)
    implementation(libs.json)
    implementation(libs.indriya)
    implementation(libs.openregex)
    implementation("io.github.java-diff-utils:java-diff-utils:4.12")
    testFixturesApi(project(":languagetool-core"))
    testFixturesApi(libs.junit4)
    testFixturesImplementation(libs.morfologik.stemming)
    testFixturesImplementation(libs.morfologik.builders)
    testFixturesImplementation(libs.jetbrains.annotations)
    testFixturesImplementation(libs.resilience4j.circuitbreaker)
    testFixturesImplementation(libs.resilience4j.micrometer)
    testImplementation(libs.logback.classic)
    testImplementation(libs.junit4)
    testImplementation("org.awaitility:awaitility:4.1.1")
    testImplementation("org.mockito:mockito-core:3.6.28")
    testImplementation(testFixtures(project(":languagetool-core")))

    testFixturesCompileOnly(libs.lombok)
    testFixturesAnnotationProcessor(libs.lombok)

    compileOnly(libs.lombok)
	annotationProcessor(libs.lombok)

	testCompileOnly(libs.lombok)
	testAnnotationProcessor(libs.lombok)
}

description = "LanguageTool Style and Grammar Checker Core"
