/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    implementation(libs.jetbrains.annotations)
    implementation(project(":languagetool-core"))
    implementation(project(":language-de"))
    testImplementation(libs.junit4)
    testImplementation(libs.morfologik.fsa)
    testImplementation(libs.morfologik.builders)
    testImplementation(project(":languagetool-core"))
}

description = "Simple German module for LanguageTool"
