/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    api(project(":languagetool-core"))
    testImplementation("junit:junit:4.13.2")
}

description = "LanguageTool common GUI classes"
