/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    implementation(libs.jetbrains.annotations)
    implementation(libs.german.pos.dict)
    implementation("de.danielnaber:jwordsplitter:4.7")
    implementation(libs.openregex)
    implementation(libs.guava)
    implementation(libs.trove4j)
    implementation(libs.commons.lang)
    implementation(libs.indriya)
    implementation(libs.hankcs)
    implementation(libs.commons.text)
    implementation(libs.morfologik.speller)
    implementation(project(":languagetool-core"))
    testImplementation(libs.junit4)
    testImplementation(project(":languagetool-core"))
    testImplementation(libs.morfologik.fsa)
    testImplementation(libs.morfologik.builders)
}

description = "German module for LanguageTool"
