/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    implementation(project(":languagetool-core"))
    implementation(libs.jetbrains.annotations)
    testImplementation(libs.junit4)
    testImplementation(project(":languagetool-core"))
}

description = "Asturian module for LanguageTool"
